# 数据清洗


## tidyverse

### 参考：

- <https://stackoverflow.com/questions/27027347/mutate-each-summarise-each-in-dplyr-how-do-i-select-certain-columns-and-give>


```{r}
require(tidyverse)
require(readxl)

# 读入excel文件
er <- read_excel("data/exams_results.xlsx")

# 查看数据
head(er)

# 将宽数据变成短数据
er %>% tidyr::gather(key = "科目", value = "分数", c("语文","数学","英语")) %>% tail
erd <- er %>% gather(key = "科目", value = "分数", -c("班级","姓名"))

# 统计每个班各个科目的总分
head(erd.heji <- erd %>% group_by(班级,科目) %>% summarise(合计 = sum(分数)))

# 再变回长数据，就好看很多了
#　这就是类似Excel数据透视表的效果了
(erl <- erd.heji %>% spread(科目,合计))

# 再来算算1班每个同学的总分

# # 方法1
er %>% filter(班级 == "六1班") %>%
  mutate(总分 = 语文 + 数学 +　英语) %>% head

# # 方法2
er %>% mutate(总分 = rowSums(.[3:5])) %>% head

# # 方法3
er %>% mutate(总分 = rowSums(select(.,语文,数学,英语))) %>% head

# # 方法4
er %>% mutate(总分 = (select(.,语文,数学,英语) %>% rowSums) ) %>% head

# # 方法5：a more complicated way would be:
er %>% select(-班级,-姓名) %>% mutate(总分 = rowSums(.)) %>% left_join(er) %>% head

# # 求每个学生三门科目的平均分
# # 虽然没必要这么复杂去算，但这里只是记录这样的用法
er %>% mutate(总分 = (select(.,语文,数学,英语) %>% rowSums)/3 ) %>% head

# # 计算语文和数学占总分的比例
# # select里面可以直接使用列名或者向量c来选择
er %>% mutate(比例 = (select(.,语文,数学) %>% rowSums) /
                  (rowSums(select(., c(3:5))))
                ) %>% head


```


## ggplot2


### 饼图

```{r}
# 再看看前面生成的erl数据框
erl

# 下面生成图表，分别计算不同班级的分数占比，和同一班级不同学科分数的占比

library(ggplot2)
library(RColorBrewer)
library(grid)

#定义好字体


#事先定制好要加图形的形状、颜色、主题等
#定制主题，要求背景全白，没有边框。然后所有的字体都是某某颜色
#定制主题，要求背景全白，没有边框。然后所有的字体都是某某颜色
mytheme<-theme_bw()+theme(legend.position="top",
                          panel.border=element_blank(),
                          panel.grid.major=element_line(linetype="dashed"),
                          panel.grid.minor=element_blank(),
                          plot.title=element_text(size=15,
                                                  colour="#003087",
                                                  family="CA"),
                          legend.text=element_text(size=9,colour="#003087",
                                                   family="CA"),
                          legend.key=element_blank(),
                          axis.text=element_text(size=10,colour="#003087",
                                                 family="CA"),
                          strip.text=element_text(size=12,colour="#EF0808",
                                                  family="CA"),
                          strip.background=element_blank()

                        )
pie_theme=mytheme+theme(axis.text=element_blank(),
                        axis.ticks=element_blank(),
                        axis.title.y=element_blank(),
                        panel.grid.major=element_blank())
#定制线的大小
myline_blue<-geom_line(colour="#085A9C",size=2)
myline_red<-geom_line(colour="#EF0808",size=2)
myarea=geom_area(colour=NA,fill="#003087",alpha=.2)
mypoint=geom_point(size=3,shape=21,colour="#003087",fill="white")
mybar=geom_bar(fill="#0C8DC4",stat="identity")
#然后是配色，考虑到样本的多样性，可以事先设定颜色，如3种颜色或7种颜色的组合
mycolour_3<-scale_fill_manual(values=c("#085A9C","#EF0808","#526373"))
mycolour_7<-scale_fill_manual(values=c("#085A9C","#EF0808","#526373",
"#FFFFE7","#FF9418","#219431","#9C52AD"))
mycolour_line_7<-scale_color_manual(values=c("#085A9C","#EF0808","#526373","#0C8DC4","#FF9418","#219431","#9C52AD"))


# 方法一
# 设置文字标签
(mylabel <- with(erl,paste0(班级, " - ", round(数学/ sum(数学) * 100, 0), "%")))
# 设置文字标签的y轴
(text.y1 <- with(erl,1-(cumsum(数学/sum(数学)) - 数学/sum(数学)/2)))
# 生成饼图
# 数学成绩做变换，将各班的数学成绩除以数学合计
erl %>% 
  ggplot(aes(x="X", y=数学/sum(数学),fill = 班级)) +
    geom_bar(stat="identity", position = "stack", width = 1) +
    mycolour_7 + pie_theme +
    geom_text(aes(y = text.y1, x = 1, label = mylabel), size = 3) +
    coord_polar(theta = "y", direction = 1)




# 方法二
# 设置显示的文字标签
(mylabel2 <- with(erl,paste0(数学, " - ", round(数学/sum(数学)*100,2),"%")))
# 设置文字标签的y坐标
(text.y2 <- with(erl,sum(数学) - cumsum(数学) + 数学/2))
# 生成饼图
# 这里对y轴，数学成绩并没有做变换
# 这种办法对设置文字标签的y坐标的公式看起来相对更简单
# 主要是对标签文字做数字变换
erl %>% 
  ggplot(aes(x = "X", y = 数学, fill = 班级)) +
  geom_bar(stat = "identity", position = "stack", width = 1) +
  geom_text(aes(x=1.3, y= text.y2, label = mylabel2, size = 2)) +
  coord_polar(theta = "y", direction = 1) +
  mytheme + pie_theme 


# 方法3
# 这个方法的geom_text的y轴坐标处理方法跟方法1一样
# position = "fill"，就是把一个班级的整体看作1
(text.y1 <- with(erl,1-(cumsum(数学/sum(数学)) - 数学/sum(数学)/2)))
erl %>% 
  ggplot(aes(x = "X", y = 数学, fill = 班级)) +
  geom_bar(stat = "identity", position = "fill", width = 1) +
  geom_text(aes(x=1.3, y= text.y1, label = mylabel2, size = 2)) +
  coord_polar(theta = "y", direction = 1) +
  mytheme + pie_theme 

```


要注意上面3种不同的方法中，geom_bar中position的不同，和aes中y轴的不同，需要不同处理geom_text的y轴坐标。


### 柱状图

```{r}
erl
# 需要先把宽数据变成短数据
(erd.zzt <- erl %>% gather(key = "科目", value = "分数", -c("班级")))

# 我们先观察四个班每个班级不同科目的总分情况
# 设置显示的文字标签
(mylabel3 <- with(erd.zzt,paste0(分数)))
# 设置文字标签的y坐标
(text.y3 <- 1:12)
# 将dodge模式摆放的三个科目的顺序按“语数英”的顺序摆放
erd.zzt$科目 <- factor(erd.zzt$科目, levels = c("语文","数学","英语"))


# 我们再将班级按总分从高到低排序
erd.zzt$班级 <- reorder(erd.zzt$班级,-erd.zzt$分数)
erd.zzt %>%
  ggplot(aes(班级,分数, fill = 科目)) +
  geom_bar(stat = "identity", position = "dodge") 


# 最后尝试一下水平摆放柱状图
erd.zzt %>%
  ggplot(aes(班级,分数, fill = 科目)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()

# 我们发现这时水平摆放的柱状图从上到下是从小到大排序
# 看来水平摆放的时候是从下面往上面数
# 要改成从上到下是降序，只能有做一次reorder了
# 这次reorder把第二个参数前面的减号-去掉
erd.zzt$班级 <- reorder(erd.zzt$班级, erd.zzt$分数)
erd.zzt %>%
  ggplot(aes(班级,分数, fill = 科目)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()

# 最后，我们在bar上添加数字
erd.zzt %>%
  ggplot(aes(班级,分数, fill = 科目)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  geom_text(aes(班级,分数*0.9,label = sprintf("%2.1f", 分数)), position=position_dodge(width = 1))

# 再看看去掉coord_flip回到竖直的样式
erd.zzt %>%
  ggplot(aes(班级,分数, fill = 科目)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(班级,分数*0.9,label = sprintf("%2.0f", 分数)), position=position_dodge(width = 1))

```

### 参考：

- <https://stackoverflow.com/questions/34889766/what-is-the-width-argument-in-position-dodge>
- <https://stackoverflow.com/questions/6017460/position-geom-text-on-dodged-barplot>
